apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    isDefault: true
    version: 1
    editable: true
    uid: loki-datasource
    url: http://localhost:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: "infinity"
          matcherRegex: "country=(\\w+)"
          name: "Country"
          url: "http://127.0.0.1:8080/country-coords.json"
